# Generated by Django 2.2.2 on 2019-09-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='parentArticle',
            new_name='parent_article',
        ),
        migrations.AlterField(
            model_name='article',
            name='disable_commenting',
            field=models.BooleanField(default=False),
        ),
    ]
