# Generated by Django 2.2.2 on 2019-09-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190921_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
